apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: traffic-generator
  namespace: default
spec:
  protocol: http
  upstreamConfig:
    defaults:
      connectTimeoutMs: 5000
      limits:
        maxConnections: 30
        maxPendingRequests: 40
        maxConcurrentRequests: 50
      passiveHealthCheck:
        interval: "5s"
        maxFailures: 10
        enforcingConsecutive5xx: 100
        maxEjectionPercent: 100
        baseEjectionTime: "10s"