---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  type: ClusterIP
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
  selector:
    app: web
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: web
spec:
  protocol: http
  upstreamConfig:
    defaults:
      connectTimeoutMs: 5000
      limits:
        maxConnections: 3
        maxPendingRequests: 4
        maxConcurrentRequests: 5
      passiveHealthCheck:
        interval: "30s" # retry period after upstream fails
        maxFailures: 2 # how many failures before ejection (circuit breaking)
        # defaults:
        # enforcingConsecutive5xx: 100 # [%] of likelihood to eject a detected failed upstream
        # maxEjectionPercent: 10 # [%] of the upstream service instances allowed to be ejected
        # baseEjectionTime: "30s" # how long to keep host ejected

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      service: web
      app: web
  template:
    metadata:
      labels:
        service: web
        app: web
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/service-meta-version: "1"
        consul.hashicorp.com/service-tags: "v1"
    spec:
      serviceAccountName: web
      containers:
        - name: web
          image: nicholasjackson/fake-service:v0.26.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9091
          env:
            - name: LISTEN_ADDR
              value: "0.0.0.0:9091"
            - name: UPSTREAM_URIS
              value: "http://api:9092"
            - name: MESSAGE
              value: "Hello World!"
            - name: NAME
              value: "web"
            - name: SERVER_TYPE
              value: "http"
