global:
  enabled: true
  name: consul
  datacenter: dc1
  image: "hashicorp/consul:1.17.0"
  acls:
    manageSystemACLs: true
  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: true
  metrics:
    enabled: true
    enableGatewayMetrics: true

server:
  enabled: true
  replicas: 3
  extraConfig: |
    {
      "log_level": "TRACE"
    }

connectInject:
  transparentProxy:
    defaultEnabled: true
  enabled: true
  default: true
  apiGateway:
    managedGatewayClass:
      serviceType: LoadBalancer
  metrics:
    defaultEnabled: true # by default, this inherits from the value global.metrics.enabled
    defaultEnableMerging: false

ui:
  enabled: true
  service:
    type: LoadBalancer
  metrics:
    enabled: true # by default, this inherits from the value global.metrics.enabled
    provider: "prometheus"
    baseURL: http://prometheus-server #prometheus-server.consul.svc.cluster.local

prometheus:
  enabled: true
