---
apiVersion: v1
kind: Service
metadata:
  name: frontend-v2
  labels:
    app: frontend-v2
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: frontend-v2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-v2
automountServiceAccountToken: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-v2-nginx-config
data:
  nginx.conf: |
    server {
      listen 3000;
      server_name localhost;

      server_tokens off;

      gzip on;
      gzip_proxied any;
      gzip_comp_level 4;
      gzip_types text/css application/javascript image/svg+xml;

      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }

      #location /api {
      #  proxy_pass http://public-api:8080;
      #}
    }
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: frontend-v2
spec:
  protocol: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend-v2
      app: frontend-v2
  template:
    metadata:
      labels:
        service: frontend-v2
        app: frontend-v2
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/service-meta-version: "2"
        consul.hashicorp.com/service-tags: "v2"
        consul.hashicorp.com/envoy-extra-args: "--log-level debug"
    spec:
      serviceAccountName: frontend-v2
      containers:
        - name: frontend-v2
          image: hashicorpdemoapp/frontend-nginx:v1.0.9
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_PUBLIC_API_URL
              value: "/"
            - name: NEXT_PUBLIC_FOOTER_FLAG
              value: "HashiCups-v2"
          volumeMounts:
            - name: frontend-v2-nginx-config
              mountPath: /etc/nginx/conf.d/
      volumes:
        - name: frontend-v2-nginx-config
          configMap:
            name: frontend-v2-nginx-config
            items:
              - key: nginx.conf
                path: default.conf