---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: product-api
spec:
  destination:
    name: product-api
  sources:
    - name: public-api
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: product-api-v2
spec:
  destination:
    name: product-api-v2
  sources:
    - name: public-api-v2
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: product-api-db
spec:
  destination:
    name: product-api-db
  sources:
    - name: product-api
      action: allow
    - name: product-api-v2
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: payments
spec:
  destination:
    name: payments
  sources:
    - name: public-api
      action: allow
    - name: public-api-v2
      action: allow
